---
- include_tasks: sourcepath.yml

- debug:
    msg: |
      Get backup status, user: '{{ username }}', profile: '{{ profile_name }}'
      Backup location: {{ remote.backup_location }}"

# Using `sudo` like on the command line works, using `become` fails

- block:
    - name: Get backup status from file system
      command: "sudo -E duply {{ profile_path|quote }} status"
      register: duply
      failed_when: duply.stdout is search("Errno") or duply.rc > 0
    - debug:
        var: duply.stdout
  when: remote.backup_location is match('^file:///')

- block:
    - name: Get backup status from S3 storage
      command: "sudo -E duply {{ profile_path|quote }} status"
      environment:
        AWS_ACCESS_KEY_ID: "{{ remote.api_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ remote.api_key_secret }}"
      register: duply
      failed_when: duply.stdout is search("Errno") or duply.rc > 0
    - debug:
        var: duply.stdout
  when: remote.backup_location is match('^s3://')

# Add more `status` setups here
