---
- name: Ensure group "{{ username }}" exists
  group:
    name: "{{ username }}"
    gid: "{{ gid | default(omit) }}"
  become: yes

- name: Create user "{{ username }}"
  user:
    name: "{{ username }}"
    uid: "{{ uid | default(omit) }}"
    group: "{{ username }}"
    groups: "{{ khoe_users_group }}"
    password: "{{ password | password_hash('sha512') }}"
  register: user
  become: yes

- name: "Create user's config directory"
  file:
    path: "{{ config_dir_user }}"
    state: directory
    owner: "{{ username }}"
    group: khoe
    mode: 0755
  become: yes

 # uid and gid are needed for docker-smb and user recovery
- name: "Get uid for '{{ username }}'"
  command: id --user {{ username }}
  register: _uid
  changed_when: false

- name: "Get gid for '{{ username }}'"
  command: id --group {{ username }}
  register: _gid
  changed_when: false

- name: Create user config
  set_fact:
    users: "{{ users | combine( { username: { 'uid': _uid.stdout | int, 'gid': _gid.stdout | int, 'shares': {} } }, recursive=True ) }}"

  # Storing in khoe ensures ability to restore user from backup (todo: backup)
- name:  write updated users config
  import_role:
    name: common
    tasks_from: write-config
  vars:
    file: "{{ config_file_users }}"
    content: "{{ users }}"
    #do_backup: yes
