# remote backup config

# backup_location: s3://ams3.digitaloceanspaces.com/khoe-cloud-backup # path is name of 'space' at DigitalOcean, no trailing slash
# remote_backup_key: QWERTYUIOP1234567890
# remote_backup_psw: qwertyuiop123456789qwertyuiop1234567890qwer
