backup_list_name: default
remote_name: local

max_age: 1Y # When a full backup reaches this age it is deleted.
max_fullbkp_age: 2M # When the last full backup reaches this age a new full backup is made.
max_fulls_with_incrs: 2 # Number of full backups for which incrementals are preserved

age: 0D
dry_run: no

minute:  '0'
hour:    '4'
day:     '*'
month:   '*'
weekday: '*'
