---
# Currently only create, delete and import are used and only programmatically with `tasks_from`.
# But hould be helpful when importing an existing key to khoe

# Usage:
# ansible-playbook playbooks/gpg.yml -e task=import -e username=example1 [-e export_path=~/gpg-export/username]

# Not implemented
# ansible-playbook playbooks/gpg.yml -e task=create -e username=example1 [-e passphrase="1234"]
# ansible-playbook playbooks/gpg.yml -e task=delete -e username=khoe [-e fingerprint=9409A43E4F16771D8FBF25CADF8D04072F675974]
# ansible-playbook playbooks/gpg.yml -e task=export -e username=example1 [-e passphrase="1234"] [-e export_path=~/gpg-export/username]

- hosts: khoe
  gather_facts: no

  pre_tasks:

    - include_role:
        name: common
        tasks_from: load-config
      vars:
        file: "{{ config_file_users }}"
        varname: users

    - set_fact:
        user: "{{ users[username] }}"

  tasks:

    - name: "Case: Import gpg keys"
      block:

        - include_role:
            name: gpg
            tasks_from: import

      when: task == "import"
