---
- name: Add Universe repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install mosh.
  apt:
    name: mosh
    state: present
